---
title: "MA5701 COVID-19 FINAL PROJECT"
author: "Ezequiel Carrillo, Evan Neibauer, Samantha Hair"
date: "11/13/2021"
output: html_document
---

```{r setup}
library(dplyr)
library(ggplot2)
```


```{r Load Data}
covid_data <- read.csv('covid_states_data.csv') %>% 
  filter(!state %in% c("MP", "DC", "PR"))
```

```{r Random Selection}
set.seed(1234) 

rand_sample <- sample(1:50, 20, replace = FALSE)
```

```{r Subset Data}
sample_covid <- covid_data[rand_sample, ]
```

```{r Clean Data}
sample_covid_clean <- sample_covid %>% 
  select(-c(fips, country, county, level, lat, locationId, long, unused1, unused2, unused3, unused4, unused5, 
            unused6, unused7, unused8, url))

attach(sample_covid_clean)
```

```{r Write cleaned sample population .csv}
write.csv(sample_covid_clean, 'sample_covid_data.csv')
```

```{r Display Data Sample Structure }
str(sample_covid_clean)

```

```{r Histograms of each variable}
sample_covid_clean %>% 
  ggplot(aes(riskLevels.overall))+
  geom_histogram(bins = 20,col="Black") +
  xlab("Overall Risk Level")+
  ylab("Frequency")+
  labs(title = "Histogram for Overall Risk Levels")

sample_covid_clean %>% 
  ggplot(aes(metrics.vaccinationsCompletedRatio))+
  geom_histogram(bins = 20,col="Black") +
  xlab("Ratio of Vaccinations Completed")+
  ylab("Frequency")+
  labs(title = "Histogram for the Vaccinations Completed Ratio") 

sample_covid_clean %>% 
  ggplot(aes(actuals.hospitalBeds.capacity))+
  geom_histogram(bins = 20, col="Black") +
  xlab("Hospital Bed Capacity")+
  ylab("Frequency")+
  labs(title = "Histogram for the Hospital Bed Capacity")

sample_covid_clean %>% 
  ggplot(aes(actuals.deaths))+
  geom_histogram(bins = 20, col="Black") +
  xlab("Number of Deaths Due to Covid")+
  ylab("Frequency")+
  labs(title = "Histogram of Deaths Due to Covid")
```

```{r Box Plot}
riskLevels.overall <- factor(riskLevels.overall, levels=c('1', '2', '3', '4', '5'))

sample_covid_clean %>% 
  ggplot()+ 
  geom_boxplot(aes(x = factor(riskLevels.overall), y = metrics.vaccinationsCompletedRatio,fill=riskLevels.overall))+
  xlab("Overall Risk Level")+
  ylab("Vaccination Ratio")+
  labs(title = "Relationship Between Vaccinations Completed and Risk Level", 
       fill = "Level of Risk")
```

```{r Scatter Plot}
sample_covid_clean %>% 
  ggplot(aes(actuals.hospitalBeds.capacity, actuals.deaths, col='Red'))+
  geom_point()+
  xlab("Hospital Bed Capacity")+
  ylab("Number of Deaths")+
  labs(title = "Relationship Between the Hospital Bed Capacity and Number of Deaths")
    print("correlation coefficient between actuals.hospitalBeds.capacity and actuals.deaths:");
    print(cor(actuals.hospitalBeds.capacity, actuals.deaths)) 
```

```{r QQ Plots}
qqnorm(actuals.hospitalBeds.capacity, main='Hospital Bed Capacity QQ Plot', xlab='Z-Value', ylab='Bed Capacity', col='Blue')
qqline(actuals.hospitalBeds.capacity)

qqnorm(actuals.deaths, main='Total Covid Deaths QQ Plot', xlab='Z-Value', ylab='Deaths',  col='Blue')
qqline(actuals.deaths)

qqnorm(metrics.vaccinationsCompletedRatio, main='Vaccination Ratio QQ Plot', xlab='Z-Value', ylab='Vaccination Ratio',  col='Blue')
qqline(metrics.vaccinationsCompletedRatio)
```

```{r Shapiro Tests for Normality}
print('The actual.hospitalBeds.capacity variable is non-normally distributed, indicated by the QQ plot and the results of the Shapiro-Wilk test')
shapiro.test(actuals.hospitalBeds.capacity)
#actual.hospitalBeds.capacity p_value < .05, So, we can reject H0;normality and accept HA; non-normal distribution
writeLines('------------------------------------------------------------------------------------------------------------\n')


print('The actuals.deaths variable is non-normally distributed, indicated by the QQ plot and the results of the Shapiro-Wilk test')
shapiro.test(actuals.deaths)
#actuals.deaths p_value < .05, So, we can reject H0;normality and accept HA; non-normal distribution
writeLines('------------------------------------------------------------------------------------------------------------\n')

print('The metrics.vaccinationsCompletedRatio variable is normally distributed, indicated by the QQ plot and the results of the Shapiro-Wilk test')
shapiro.test(metrics.vaccinationsCompletedRatio)
#metrics.vaccinationsCompletedRatio p_value > .05, So we can fail to reject H0; normal distribution
```

```{r Summary Statistics}
writeLines('riskLevels.overall descriptive statistics:\n')
summary(sample_covid_clean$riskLevels.overall)
writeLines('------------------------------------------------------------------------------------------------------------\n')

writeLines('metrics.vaccinationsCompletedRatio descriptive statistics:\n')
summary(sample_covid_clean$metrics.vaccinationsCompletedRatio)
writeLines('------------------------------------------------------------------------------------------------------------\n')

writeLines('actuals.deaths descriptive statistics:\n')
summary(sample_covid_clean$actuals.deaths)
writeLines('------------------------------------------------------------------------------------------------------------\n')

writeLines('actuals.hospitalBeds.capacity descriptive statistics:\n')
summary(sample_covid_clean$actuals.hospitalBeds.capacity)
```
```{r Install pastec package}
install.packages("pastecs")
library(pastecs)
```
```{r More Summary Stats on Variables of Interest}
variables_of_interest=sample_covid_clean[1:20,c(10,17,21,33)]
#variables_of_interest
summary_stats <- stat.desc(variables_of_interest)
round(summary_stats,2)
```
```{r Summary Stats on All Quantitative Variables}
all_quantitative_variables=sample_covid_clean[1:20,c(2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36)]
#all_quantitative_variables
all_stats <- stat.desc(all_quantitative_variables)
round(all_stats,1)
```

```{r Simple Linear Regression}

# Simple Linear Regression Model
lm.model <- lm((actuals.deaths/population)~(actuals.hospitalBeds.capacity/population))

# Check Assumptions
res <- residuals(lm.model) #residuals
fit <- fitted.values(lm.model) #fitted values
qqnorm(res) #check for normality
qqline(res)
plot(res~fit) #check for homoscedasticity
abline(h=0)
boxplot(res)
hist(res)
plot((actuals.deaths/population)~(actuals.hospitalBeds.capacity/population)) #check if lm is appropriate

# Check p-value for hypothesis test
summary(lm.model)

```

```{r ANOVA check, aggregate functions on variables of interest}
boxplot(metrics.vaccinationsCompletedRatio~riskLevels.overall) # once again check box plots for a rough view of each risk level and its comparative completed vacciantion ratio
#Since only levels 2 & 3 have sufficient data points we will not use ANOVA
aggregate(metrics.vaccinationsCompletedRatio~riskLevels.overall, FUN=mean) #as we get a higher risk level, the ratio of vaccinated goes down
aggregate(metrics.vaccinationsCompletedRatio~riskLevels.overall, FUN=mean)[c(2,3),] #see avg vaccination ratio for risk levels 2,3 since these are the levels of interest
aggregate(metrics.vaccinationsCompletedRatio~riskLevels.overall, FUN=sd)[c(2,3),]
```
```{r F-test to check for difference in variance}
#f-test to test for equal variances
sample_count=count(sample_covid_clean)#check count
sample_ordered=sample_covid_clean[
  with(sample_covid_clean, order(riskLevels.overall)),
]

data = sample_ordered[sample_ordered$riskLevels.overall != c(1,5), ]
var.test(data$metrics.vaccinationsCompletedRatio~data$riskLevels.overall, ratio=1, alternative = "two.sided")
#the variances are roughly equal by teh f-test, hence we will use the pooled t-test for testing the differnece in means of both vaccination ratio between risk levels 2 & 3
```
```{r Pooled t-test}
aggregate(data$metrics.vaccinationsCompletedRatio~data$riskLevels.overall,FUN=mean)
boxplot(data$metrics.vaccinationsCompletedRatio~data$riskLevels.overall)

t.test(data$metrics.vaccinationsCompletedRatio~data$riskLevels.overall, alt='t', conf.level=.95, var.equal=TRUE)
#By the pooled Sample t-test, we retain H0: mu1=mu2 at the .95 confidence level

```
```{r Kruskall Wallis test on risk levels}
print('Non parametric test to check H0: population medians are equal. against HA: population medians are not equal.')

#assumptions:
#1) One independent variable with 2 or more levels -Satisfied (risk levels is ordinal and has 5 levels)
#2) Ordinal or ratio scale for dependent variable -Satisfied (vacination ratio is numeric ratio)
#3)Independent random samples for the k groups  -Satisfied via our sampling scheme
#4)All k groups have the same "shape" -NOT satisfied
install.packages('MASS')
library('MASS') # Load MASS for the birthwt data set

# Use risk level as the faceting variable
ggplot(covid_data, aes(x = metrics.vaccinationsCompletedRatio)) +
  geom_histogram(fill = "white", colour = "black") +
  facet_grid(riskLevels.overall ~ .)
 
writeLines('all k groups do not share the same dsitribution shape, mainly due to a lack of data points in levels other than 2 & 3. Even though we are not testing if the k groups have the same shape, by the non parametric Kruskal Wallis test we fails to reject H0: there is some difference between the vaccination ratios for states with different risk levels')

kruskal.test(metrics.vaccinationsCompletedRatio~riskLevels.overall,data = covid_data)
#Results: Retain H0: There is no difference in median vaccionation ratio between states with different risk levels. p=0.6934


```
